# Generated by Django 4.1 on 2022-11-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(default=None, upload_to="shop_image/"),
            preserve_default=False,
        ),
    ]
