# Generated by Django 4.1 on 2022-11-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(upload_to="img/shop_image/"),
        ),
    ]
