# Generated by Django 4.1 on 2022-11-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_product_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(upload_to="img_product"),
        ),
    ]
