# Generated by Django 4.1 on 2022-11-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_orderitem_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="image_url",
        ),
    ]
