# Generated by Django 4.1 on 2022-12-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_recipe_image_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="code",
            field=models.CharField(
                default=0, max_length=255, verbose_name="recipe_code"
            ),
        ),
    ]
