# Generated by Django 4.1 on 2022-12-06 10:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_recipe_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="product_list",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (1, "Говядина - 500 г"),
                    (2, "Свёкла - 1 шт"),
                    (3, "Картофель - 2 шт"),
                    (4, "Капуста белокочанная - 200 г"),
                    (5, "Морковь - 1 шт"),
                    (6, "Лук репчатый - 1 шт"),
                ],
                max_length=10000,
            ),
        ),
    ]
