# Generated by Django 4.1 on 2022-12-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_recipe_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_thousand_on_thousand",
            field=models.ImageField(null=True, upload_to="image_thousand_on_thousand"),
        ),
    ]
