# Generated by Django 4.1 on 2022-12-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_order_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
    ]
